# Generated by Django 5.2.9 on 2025-12-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], db_index=True, default='customer', max_length=20, verbose_name='Role'),
        ),
    ]
